import type { Lesson } from "@/lib/types";

export const engineeringLessons: Lesson[] = [
  {
    id: "engineering-design-process",
    subject: "engineering",
    order: 1,
    title: "The Engineering Design Process",
    teachingBlurb:
      "Engineers solve problems by defining the problem and its constraints first, then imagining and planning possible solutions, building a prototype, testing it, and improving it based on what they learn. A constraint is a limit you must design within (like budget, time, or materials). A success criterion is a measurable requirement the finished design must meet (like holding a certain weight). Failing a test isn't a dead end — it's information that drives the next, better design.",
    questions: [
      {
        id: "engineering-design-process-q1",
        type: "multiple-choice",
        prompt: "Before designing a solution, an engineer should FIRST...",
        choices: [
          "Clearly define the problem and its constraints and success criteria",
          "Immediately start building a prototype",
          "Guess the size of the final product",
          "Sell the idea to a customer",
        ],
        correctChoiceIndex: 0,
        explanation: "Without a clear problem definition and constraints, it's impossible to know what a successful design even looks like.",
      },
      {
        id: "engineering-design-process-q2",
        type: "multiple-choice",
        prompt: "A 'constraint' in an engineering design challenge is...",
        choices: [
          "A limit you must design within, such as budget, materials, or time",
          "A reward for good design",
          "An optional suggestion you can ignore",
          "A type of test the product must pass",
        ],
        correctChoiceIndex: 0,
        explanation: "Constraints are the boundaries of the problem — resources or rules you cannot exceed while designing your solution.",
      },
      {
        id: "engineering-design-process-q3",
        type: "multiple-choice",
        prompt: "A 'success criterion' in an engineering challenge is...",
        choices: [
          "A measurable requirement the finished design must meet, like holding 2 kg or costing under $10",
          "A random guess about the outcome",
          "The same thing as a constraint",
          "A tool used to build the prototype",
        ],
        correctChoiceIndex: 0,
        explanation: "Success criteria describe what the finished design has to DO or achieve, so you can objectively test whether it worked.",
      },
      {
        id: "engineering-design-process-q4",
        type: "multiple-choice",
        prompt: "After building and testing a first prototype that fails to meet the requirements, an engineer should...",
        choices: [
          "Analyze what went wrong and redesign — failure is a normal part of the process",
          "Give up on the project entirely",
          "Ignore the results and submit the same design anyway",
          "Blame the materials and stop testing",
        ],
        correctChoiceIndex: 0,
        explanation: "The design process is iterative: each failed test reveals specific weaknesses that guide the next, improved version.",
      },
      {
        id: "engineering-design-process-q5",
        type: "multiple-choice",
        prompt: "A team is asked to design a phone stand using no more than $2 of material and no more than 10 minutes of build time, that must hold a phone upright at a 45° angle. Which of these is a CONSTRAINT rather than a success criterion?",
        choices: [
          "The $2 material budget and 10-minute time limit",
          "The requirement that the phone stands at 45°",
          "Both are exactly the same kind of requirement",
          "Neither one is relevant to the design",
        ],
        correctChoiceIndex: 0,
        explanation: "Budget and time are resource limits you must work within (constraints), while holding the phone at 45° is what the finished design must achieve (a success criterion).",
      },
      {
        id: "engineering-design-process-q6",
        type: "multiple-choice",
        prompt: "Why do engineers build and test multiple prototypes instead of just one final version?",
        choices: [
          "Testing reveals weaknesses early, when they're cheaper and easier to fix",
          "Building more prototypes is required by law",
          "It guarantees the very first idea was wrong",
          "It wastes time on purpose",
        ],
        correctChoiceIndex: 0,
        explanation: "Catching a flaw in an early prototype is far cheaper and faster to fix than discovering it in a finished product.",
      },
    ],
  },
  {
    id: "engineering-forces-and-structures",
    subject: "engineering",
    order: 2,
    title: "Structures & Forces",
    teachingBlurb:
      "Every structure has to handle a load — the weight or force it must support. Compression is a squeezing/pushing force (like a column holding up a roof); tension is a stretching/pulling force (like a cable holding a swing). Engineers often build with triangles because a triangle's shape resists deformation under load, unlike a square or rectangle, which can collapse sideways.",
    questions: [
      {
        id: "engineering-forces-and-structures-q1",
        type: "multiple-choice",
        prompt: "A cable holding up a swing is under which type of force?",
        choices: ["Tension (being pulled/stretched)", "Compression (being squeezed)", "Torsion (being twisted)", "No force at all"],
        correctChoiceIndex: 0,
        explanation: "The swing's weight pulls down on the cable, stretching it — that's tension.",
      },
      {
        id: "engineering-forces-and-structures-q2",
        type: "multiple-choice",
        prompt: "A column holding up a roof, being pressed straight down on, is mainly under...",
        choices: ["Compression (being squeezed)", "Tension (being stretched)", "Friction only", "Magnetism"],
        correctChoiceIndex: 0,
        explanation: "The roof's weight pushes down on the column, squeezing it — that's compression.",
      },
      {
        id: "engineering-forces-and-structures-q3",
        type: "multiple-choice",
        prompt: "Why do engineers use triangle shapes in bridge trusses instead of squares?",
        choices: [
          "Triangles keep their shape under load and don't collapse the way squares can",
          "Triangles are always cheaper to build than squares",
          "Triangles weigh less no matter the material used",
          "Squares are not allowed in bridge design",
        ],
        correctChoiceIndex: 0,
        explanation: "A triangle's fixed angles make it rigid — it can't flex into a different shape the way a square or rectangle can fold sideways under force.",
      },
      {
        id: "engineering-forces-and-structures-q4",
        type: "numeric",
        prompt: "A shelf bracket must support a load of 12 kg spread evenly across 3 identical support brackets. How many kg of load does each bracket carry?",
        correctAnswer: 4,
        unit: "kg",
        explanation: "Dividing the total load evenly: 12 kg ÷ 3 brackets = 4 kg per bracket.",
      },
      {
        id: "engineering-forces-and-structures-q5",
        type: "numeric",
        prompt: "A cable is rated to safely hold 200 N of tension force. If a sign hanging from it exerts 45 N, how many more newtons of force could be added before reaching the rated limit?",
        correctAnswer: 155,
        unit: "N",
        explanation: "200 N (limit) - 45 N (current load) = 155 N of remaining capacity.",
      },
      {
        id: "engineering-forces-and-structures-q6",
        type: "multiple-choice",
        prompt: "A wooden beam bends when weight is placed on top of it. The top surface of the beam is being...",
        choices: ["Compressed", "Stretched (tension)", "Twisted", "Left completely unaffected"],
        correctChoiceIndex: 0,
        explanation: "When a beam bends, its top fibers get squeezed together (compression) while its bottom fibers get pulled apart (tension).",
      },
    ],
  },
  {
    id: "engineering-bridge-design-challenge",
    subject: "engineering",
    order: 3,
    title: "Bridge Design Challenge",
    teachingBlurb:
      "Real design challenges come with limited resources. Imagine you're designing a popsicle-stick bridge across a 20 cm gap: it must hold at least 5 kg without breaking, and you have a budget of 30 'material points'. Each supporting popsicle stick costs 1 point and safely holds 0.5 kg in a truss position; each glue joint needed to connect sticks costs 1 point but adds no load capacity on its own. Good engineers also build in a safety margin, designing for more than the bare minimum requirement, since real-world materials and loads vary.",
    questions: [
      {
        id: "engineering-bridge-design-challenge-q1",
        type: "numeric",
        prompt: "Using only supporting popsicle sticks (each holding 0.5 kg), how many sticks are needed at minimum to reach the 5 kg requirement?",
        correctAnswer: 10,
        explanation: "5 kg ÷ 0.5 kg per stick = 10 sticks.",
      },
      {
        id: "engineering-bridge-design-challenge-q2",
        type: "numeric",
        prompt: "If you use exactly 10 supporting sticks (10 points) plus 8 glue joints (8 points) to connect them, how many of your 30 material points remain unused?",
        correctAnswer: 12,
        explanation: "30 total points - 10 (sticks) - 8 (glue joints) = 12 points remaining.",
      },
      {
        id: "engineering-bridge-design-challenge-q3",
        type: "multiple-choice",
        prompt: "Your prototype holds exactly 5 kg then snaps. What's the SAFEST engineering conclusion?",
        choices: [
          "Add a safety margin — design for more than the minimum required load, since real conditions vary",
          "5 kg is exactly enough — no changes are needed",
          "Remove sticks to save budget since it worked once",
          "Ignore the result and use the design as-is",
        ],
        correctChoiceIndex: 0,
        explanation: "Real-world materials and loads vary, so engineers design with a safety margin above the minimum to avoid failing right at the edge.",
      },
      {
        id: "engineering-bridge-design-challenge-q4",
        type: "multiple-choice",
        prompt: "You have two design options using the same 20 points of sticks: Option A arranges 12 sticks in triangles (holds 7 kg). Option B arranges 12 sticks in a single flat row (holds 4 kg). Given the 5 kg requirement, which should you choose and why?",
        choices: [
          "Option A — it meets the 5 kg requirement with a safety margin, at the same cost",
          "Option B — flat rows always look neater",
          "Either — since they cost the same, it doesn't matter",
          "Option B — because it uses less glue",
        ],
        correctChoiceIndex: 0,
        explanation: "Both cost the same, but only Option A (using triangles for rigidity) clears the 5 kg requirement with room to spare.",
      },
      {
        id: "engineering-bridge-design-challenge-q5",
        type: "numeric",
        prompt: "A stronger design uses 6 thicker sticks, each safely holding 1.2 kg. What is the total load capacity of this design, in kg?",
        correctAnswer: 7.2,
        tolerance: 0.01,
        unit: "kg",
        explanation: "6 sticks × 1.2 kg each = 7.2 kg total capacity.",
      },
      {
        id: "engineering-bridge-design-challenge-q6",
        type: "multiple-choice",
        prompt: "Design A (triangles, from question 4) holds 7 kg for 20 points total. Design C (thick sticks, from question 5) holds 7.2 kg for 26 points total. Which is the better value if your ONLY goal is the lowest cost while still meeting the 5 kg requirement?",
        choices: [
          "Design A — it meets the requirement and costs less",
          "Design C — it holds slightly more weight, so it's automatically better",
          "Neither design meets the requirement",
          "Cost never matters in engineering decisions",
        ],
        correctChoiceIndex: 0,
        explanation: "Both designs clear the 5 kg requirement, but Design A does it for 6 fewer points — when a requirement is already met, the cheaper option is the better value.",
      },
    ],
  },
  {
    id: "engineering-simple-machines",
    subject: "engineering",
    order: 4,
    title: "Simple Machines & Mechanical Advantage",
    teachingBlurb:
      "Simple machines make work easier by trading force for distance, not by creating energy from nothing. A lever's mechanical advantage equals its effort arm length divided by its resistance (load) arm length — a bigger number means less force is needed to lift the same load. A ramp's mechanical advantage equals its length divided by its height, so a longer, gentler ramp needs less force but must be pushed over a greater distance.",
    questions: [
      {
        id: "engineering-simple-machines-q1",
        type: "multiple-choice",
        prompt: "A simple machine makes work easier mainly by...",
        choices: [
          "Changing the amount of force needed, the distance over which it's applied, or the direction of force",
          "Creating extra energy out of nothing",
          "Making objects weigh less",
          "Eliminating the need for any force at all",
        ],
        correctChoiceIndex: 0,
        explanation: "Simple machines trade off force and distance (or redirect force) — they never create energy, since energy is conserved.",
      },
      {
        id: "engineering-simple-machines-q2",
        type: "numeric",
        prompt: "A lever has an effort arm of 6 m and a resistance (load) arm of 2 m. What is its mechanical advantage (effort arm ÷ load arm)?",
        correctAnswer: 3,
        explanation: "Mechanical advantage = 6 m ÷ 2 m = 3.",
      },
      {
        id: "engineering-simple-machines-q3",
        type: "numeric",
        prompt: "Using the lever from the question above (mechanical advantage = 3), how much effort force (in N) is needed to lift a 300 N load?",
        correctAnswer: 100,
        unit: "N",
        explanation: "Effort force = load ÷ mechanical advantage = 300 N ÷ 3 = 100 N.",
      },
      {
        id: "engineering-simple-machines-q4",
        type: "numeric",
        prompt: "A ramp is 8 m long and rises to a height of 2 m. What is its mechanical advantage (ramp length ÷ height)?",
        correctAnswer: 4,
        explanation: "Mechanical advantage = 8 m ÷ 2 m = 4.",
      },
      {
        id: "engineering-simple-machines-q5",
        type: "multiple-choice",
        prompt: "Compared to a steeper, shorter ramp to the same height, a longer, gentler ramp requires...",
        choices: [
          "Less force, but the object must be pushed a greater distance",
          "More force over a shorter distance",
          "The exact same force and distance",
          "No force at all",
        ],
        correctChoiceIndex: 0,
        explanation: "A longer ramp has a higher mechanical advantage, reducing the force needed — but you make up for it by pushing over a longer distance.",
      },
      {
        id: "engineering-simple-machines-q6",
        type: "multiple-choice",
        prompt: "You need to move a heavy boulder with only a long metal bar and a small rock as a pivot (fulcrum). Where should you place the fulcrum to get the MOST mechanical advantage?",
        choices: [
          "Close to the boulder (making the effort arm much longer than the load arm)",
          "Exactly in the middle of the bar",
          "Close to your hands (making the effort arm shorter)",
          "It doesn't matter where the fulcrum is placed",
        ],
        correctChoiceIndex: 0,
        explanation: "Mechanical advantage is effort arm ÷ load arm, so placing the fulcrum near the boulder maximizes the effort arm's length relative to the load arm.",
      },
    ],
  },
  {
    id: "engineering-circuits-ohms-law",
    subject: "engineering",
    order: 5,
    title: "Circuits & Ohm's Law",
    teachingBlurb:
      "An electrical circuit has three key quantities: voltage (V, the electrical push, measured in volts), current (I, the flow of charge, measured in amps), and resistance (R, how much the circuit resists that flow, measured in ohms). Ohm's Law ties them together: V = I × R. Engineers use this to figure out how much current a design will draw, and to keep circuits within safe limits.",
    questions: [
      {
        id: "engineering-circuits-ohms-law-q1",
        type: "multiple-choice",
        prompt: "In Ohm's Law, V = I × R, what does 'I' represent?",
        choices: ["Current (measured in amps)", "Voltage (measured in volts)", "Resistance (measured in ohms)", "Power (measured in watts)"],
        correctChoiceIndex: 0,
        explanation: "I stands for current, the rate at which electric charge flows through the circuit, measured in amps (A).",
      },
      {
        id: "engineering-circuits-ohms-law-q2",
        type: "numeric",
        prompt: "A circuit has a voltage of 12 V and a resistance of 4 ohms. Using V = I × R, what is the current I, in amps?",
        correctAnswer: 3,
        unit: "A",
        explanation: "Rearranging: I = V ÷ R = 12 V ÷ 4 Ω = 3 A.",
      },
      {
        id: "engineering-circuits-ohms-law-q3",
        type: "numeric",
        prompt: "A circuit needs a current of 2 A and has a resistance of 5 ohms. What voltage, in volts, is required?",
        correctAnswer: 10,
        unit: "V",
        explanation: "V = I × R = 2 A × 5 Ω = 10 V.",
      },
      {
        id: "engineering-circuits-ohms-law-q4",
        type: "multiple-choice",
        prompt: "If you increase the resistance in a circuit while keeping voltage constant, the current will...",
        choices: ["Decrease", "Increase", "Stay exactly the same", "Become negative"],
        correctChoiceIndex: 0,
        explanation: "Since I = V ÷ R, increasing R while V stays fixed makes the current I smaller.",
      },
      {
        id: "engineering-circuits-ohms-law-q5",
        type: "numeric",
        prompt: "Your robot's motor needs 6 V to run and the circuit resistance is 3 ohms. How many amps of current will flow through it?",
        correctAnswer: 2,
        unit: "A",
        explanation: "I = V ÷ R = 6 V ÷ 3 Ω = 2 A.",
      },
      {
        id: "engineering-circuits-ohms-law-q6",
        type: "multiple-choice",
        prompt: "You're designing a circuit and your battery is rated for a maximum safe current of 2 A. Using a 6 V battery, what is the MINIMUM resistance (in ohms) you should design the circuit with to stay within the safe current limit? (R = V ÷ I)",
        choices: ["3 ohms (6 V ÷ 2 A)", "12 ohms", "0.33 ohms", "6 ohms"],
        correctChoiceIndex: 0,
        explanation: "R = V ÷ I = 6 V ÷ 2 A = 3 ohms. Any resistance below 3 ohms would push the current above the 2 A safety limit.",
      },
    ],
  },
  {
    id: "engineering-materials-tradeoffs",
    subject: "engineering",
    order: 6,
    title: "Materials & Trade-offs",
    teachingBlurb:
      "No material is best at everything — engineers pick materials by weighing trade-offs between strength, weight, and cost against the specific constraints of their project. Imagine designing a drone frame that must weigh under 200 g, survive impacts (at least medium impact resistance), and cost under $15. The options: balsa wood (40 g, low impact resistance, $2), carbon fiber (55 g, high impact resistance, $18), aluminum (210 g, high impact resistance, $9), and ABS plastic (90 g, medium impact resistance, $7).",
    questions: [
      {
        id: "engineering-materials-tradeoffs-q1",
        type: "multiple-choice",
        prompt: "Given the $15 budget constraint, which material is immediately ruled out regardless of its other properties?",
        choices: [
          "Carbon fiber ($18, over budget)",
          "Balsa wood ($2)",
          "Aluminum ($9)",
          "ABS plastic ($7)",
        ],
        correctChoiceIndex: 0,
        explanation: "Carbon fiber costs $18, which exceeds the $15 budget constraint no matter how strong or light it is.",
      },
      {
        id: "engineering-materials-tradeoffs-q2",
        type: "multiple-choice",
        prompt: "Which material is ruled out by the 200 g weight limit alone?",
        choices: ["Aluminum (210 g)", "Balsa wood (40 g)", "ABS plastic (90 g)", "Carbon fiber (55 g)"],
        correctChoiceIndex: 0,
        explanation: "Aluminum weighs 210 g, which is over the 200 g weight limit, regardless of its strength or cost.",
      },
      {
        id: "engineering-materials-tradeoffs-q3",
        type: "multiple-choice",
        prompt: "Which material is ruled out because its impact resistance is too low for the 'survive impacts' requirement?",
        choices: ["Balsa wood (low impact resistance)", "ABS plastic", "Carbon fiber", "Aluminum"],
        correctChoiceIndex: 0,
        explanation: "Balsa wood only has low impact resistance, which fails the 'at least medium' requirement even though it's cheap and light.",
      },
      {
        id: "engineering-materials-tradeoffs-q4",
        type: "multiple-choice",
        prompt: "Considering ALL THREE constraints together (under 200 g, at least medium impact resistance, under $15), which single material satisfies every requirement?",
        choices: ["ABS plastic", "Balsa wood", "Carbon fiber", "Aluminum"],
        correctChoiceIndex: 0,
        explanation: "ABS plastic (90 g, medium impact resistance, $7) is the only option that clears all three constraints at once — the others each fail one.",
      },
      {
        id: "engineering-materials-tradeoffs-q5",
        type: "numeric",
        prompt: "The chosen frame material (ABS plastic) weighs 90 g. If the drone also needs a 45 g battery and 25 g of electronics, what is the total weight, in grams, of frame + battery + electronics?",
        correctAnswer: 160,
        unit: "g",
        explanation: "90 g + 45 g + 25 g = 160 g total.",
      },
      {
        id: "engineering-materials-tradeoffs-q6",
        type: "multiple-choice",
        prompt: "The total weight from the question above (160 g) is compared to the 200 g limit. What does this tell the engineer?",
        choices: [
          "There is a 40 g margin left for additional components like propellers and wiring",
          "The design has already failed the weight constraint",
          "No more weight can ever be added, including wiring",
          "The budget constraint has been exceeded",
        ],
        correctChoiceIndex: 0,
        explanation: "200 g - 160 g = 40 g of remaining weight budget for any parts not yet accounted for.",
      },
    ],
  },
];
