import type { Lesson } from "@/lib/types";

export const mathLessons: Lesson[] = [
  {
    id: "math-variables-expressions",
    subject: "math",
    order: 1,
    title: "Variables & Expressions",
    teachingBlurb:
      "A variable is a letter that stands in for a number we don't know yet, like x or n. An algebraic expression combines variables, numbers, and operations (+, -, ×, ÷) — but unlike an equation, it has no equals sign, so it can't be 'solved,' only simplified or evaluated for a given value.",
    questions: [
      {
        id: "math-variables-expressions-q1",
        type: "multiple-choice",
        prompt: "In the expression 3x + 7, what is the coefficient of x?",
        choices: ["3", "7", "x", "10"],
        correctChoiceIndex: 0,
        explanation:
          "The coefficient is the number multiplied by the variable. Here 3 is multiplied by x, so 3 is the coefficient — 7 is a separate constant term.",
      },
      {
        id: "math-variables-expressions-q2",
        type: "numeric",
        prompt: "Evaluate 5x - 2 when x = 4.",
        correctAnswer: 18,
        explanation: "Substitute x = 4: 5(4) - 2 = 20 - 2 = 18.",
      },
      {
        id: "math-variables-expressions-q3",
        type: "multiple-choice",
        prompt: "Which expression represents 'a number n increased by 9'?",
        choices: ["n + 9", "9n", "n - 9", "n / 9"],
        correctChoiceIndex: 0,
        explanation:
          "'Increased by' means addition, so n + 9. The other choices represent multiplying, subtracting from, or dividing n instead.",
      },
      {
        id: "math-variables-expressions-q4",
        type: "numeric",
        prompt: "Evaluate 2x + 3y when x = 3 and y = 5.",
        correctAnswer: 21,
        explanation: "2(3) + 3(5) = 6 + 15 = 21.",
      },
      {
        id: "math-variables-expressions-q5",
        type: "multiple-choice",
        prompt: "What is the constant term in the expression 6x - 11?",
        choices: ["6", "-11", "11", "x"],
        correctChoiceIndex: 1,
        explanation:
          "A constant term has no variable attached to it. -11 stands alone, while 6 is the coefficient of x.",
      },
      {
        id: "math-variables-expressions-q6",
        type: "numeric",
        prompt: "A number x is tripled and then 4 is added. What is the result when x = 6?",
        correctAnswer: 22,
        explanation: "Tripling x gives 3x, then add 4: 3(6) + 4 = 18 + 4 = 22.",
      },
    ],
  },
  {
    id: "math-order-of-operations",
    subject: "math",
    order: 2,
    title: "Order of Operations",
    teachingBlurb:
      "When an expression has more than one operation, everyone needs to do the steps in the same order to get the same answer. That order is: Parentheses, Exponents, Multiplication and Division (left to right), then Addition and Subtraction (left to right) — remembered with the acronym PEMDAS.",
    questions: [
      {
        id: "math-order-of-operations-q1",
        type: "numeric",
        prompt: "Evaluate: 3 + 4 × 2",
        correctAnswer: 11,
        explanation: "Multiplication happens before addition: 4 × 2 = 8, then 3 + 8 = 11.",
      },
      {
        id: "math-order-of-operations-q2",
        type: "numeric",
        prompt: "Evaluate: (3 + 4) × 2",
        correctAnswer: 14,
        explanation: "Parentheses first: 3 + 4 = 7, then 7 × 2 = 14.",
      },
      {
        id: "math-order-of-operations-q3",
        type: "multiple-choice",
        prompt: "Which operation should you perform first in 8 - 2 × 3 + 1?",
        choices: [
          "Multiplication (2 × 3)",
          "Subtraction (8 - 2)",
          "Addition (3 + 1)",
          "It doesn't matter, work left to right",
        ],
        correctChoiceIndex: 0,
        explanation:
          "Multiplication outranks addition and subtraction in PEMDAS, so 2 × 3 = 6 is computed first, giving 8 - 6 + 1 = 3.",
      },
      {
        id: "math-order-of-operations-q4",
        type: "numeric",
        prompt: "Evaluate: 2^3 + 4 ÷ 2",
        correctAnswer: 10,
        explanation: "Exponent first: 2^3 = 8. Then division: 4 ÷ 2 = 2. Finally 8 + 2 = 10.",
      },
      {
        id: "math-order-of-operations-q5",
        type: "numeric",
        prompt: "Evaluate: 5(3 + 2) - 4",
        correctAnswer: 21,
        explanation: "Parentheses first: 3 + 2 = 5. Then multiply: 5 × 5 = 25. Then subtract: 25 - 4 = 21.",
      },
      {
        id: "math-order-of-operations-q6",
        type: "multiple-choice",
        prompt: "What does PEMDAS stand for, in order?",
        choices: [
          "Parentheses, Exponents, Multiplication/Division, Addition/Subtraction",
          "Parentheses, Addition, Multiplication, Subtraction",
          "Exponents, Parentheses, Addition, Multiplication",
          "Multiplication, Division, Addition, Subtraction, Parentheses",
        ],
        correctChoiceIndex: 0,
        explanation:
          "PEMDAS: Parentheses, Exponents, Multiplication/Division (left to right), then Addition/Subtraction (left to right).",
      },
    ],
  },
  {
    id: "math-combining-like-terms",
    subject: "math",
    order: 3,
    title: "Combining Like Terms",
    teachingBlurb:
      "Like terms have the exact same variable raised to the exact same power (3x and 5x are like terms; 3x and 5x² are not). To simplify an expression, add or subtract the coefficients of like terms while keeping the variable part unchanged.",
    questions: [
      {
        id: "math-combining-like-terms-q1",
        type: "multiple-choice",
        prompt: "Simplify: 3x + 5x",
        choices: ["8x", "15x", "8x^2", "Cannot be simplified"],
        correctChoiceIndex: 0,
        explanation: "3x and 5x are like terms, so add the coefficients: 3 + 5 = 8, giving 8x.",
      },
      {
        id: "math-combining-like-terms-q2",
        type: "multiple-choice",
        prompt: "Simplify: 7y - 2y + 4",
        choices: ["5y + 4", "9y + 4", "5y - 4", "2y + 4"],
        correctChoiceIndex: 0,
        explanation: "Combine the y terms: 7y - 2y = 5y. The constant 4 has no like term, so it stays: 5y + 4.",
      },
      {
        id: "math-combining-like-terms-q3",
        type: "multiple-choice",
        prompt: "Which two terms below are like terms? 3x, 5x^2, 7x, 2y",
        choices: ["3x and 7x", "3x and 5x^2", "5x^2 and 2y", "7x and 2y"],
        correctChoiceIndex: 0,
        explanation:
          "3x and 7x both have the variable x raised to the first power, so they're like terms. 5x^2 has a different power, and 2y has a different variable.",
      },
      {
        id: "math-combining-like-terms-q4",
        type: "numeric",
        prompt: "Simplify 2x + 3x, then evaluate the result when x = 4.",
        correctAnswer: 20,
        explanation: "2x + 3x simplifies to 5x. Evaluating at x = 4: 5(4) = 20.",
      },
      {
        id: "math-combining-like-terms-q5",
        type: "multiple-choice",
        prompt: "Simplify: 6a + 3b - 2a + b",
        choices: ["4a + 4b", "4a + 2b", "8a + 4b", "4a + 3b - 2a"],
        correctChoiceIndex: 0,
        explanation: "Combine a terms: 6a - 2a = 4a. Combine b terms: 3b + b = 4b. Result: 4a + 4b.",
      },
      {
        id: "math-combining-like-terms-q6",
        type: "numeric",
        prompt: "Simplify 9x - 4x + 2x, then evaluate the result when x = 5.",
        correctAnswer: 35,
        explanation: "9x - 4x + 2x simplifies to 7x. Evaluating at x = 5: 7(5) = 35.",
      },
    ],
  },
  {
    id: "math-one-step-equations",
    subject: "math",
    order: 4,
    title: "Solving One-Step Equations",
    teachingBlurb:
      "An equation is a statement that two expressions are equal. To solve for a variable, undo whatever is being done to it using the inverse operation — and always do the same thing to both sides so the equation stays balanced.",
    questions: [
      {
        id: "math-one-step-equations-q1",
        type: "numeric",
        prompt: "Solve for x: x + 7 = 12",
        correctAnswer: 5,
        explanation: "Subtract 7 from both sides: x = 12 - 7 = 5.",
      },
      {
        id: "math-one-step-equations-q2",
        type: "numeric",
        prompt: "Solve for x: x - 9 = 4",
        correctAnswer: 13,
        explanation: "Add 9 to both sides: x = 4 + 9 = 13.",
      },
      {
        id: "math-one-step-equations-q3",
        type: "numeric",
        prompt: "Solve for x: 5x = 35",
        correctAnswer: 7,
        explanation: "Divide both sides by 5: x = 35 ÷ 5 = 7.",
      },
      {
        id: "math-one-step-equations-q4",
        type: "numeric",
        prompt: "Solve for x: x / 3 = 6",
        correctAnswer: 18,
        explanation: "Multiply both sides by 3: x = 6 × 3 = 18.",
      },
      {
        id: "math-one-step-equations-q5",
        type: "multiple-choice",
        prompt: "To solve x + 8 = 20, what should you do to both sides?",
        choices: ["Subtract 8", "Add 8", "Multiply by 8", "Divide by 8"],
        correctChoiceIndex: 0,
        explanation: "x is being added to 8, so the inverse operation — subtracting 8 — isolates x.",
      },
      {
        id: "math-one-step-equations-q6",
        type: "numeric",
        prompt: "Solve for x: -4x = 28",
        correctAnswer: -7,
        explanation: "Divide both sides by -4: x = 28 ÷ (-4) = -7.",
      },
    ],
  },
  {
    id: "math-two-step-equations",
    subject: "math",
    order: 5,
    title: "Solving Two-Step Equations",
    teachingBlurb:
      "Two-step equations combine two operations, like 2x + 3 = 11. Undo addition or subtraction first, then undo multiplication or division — working outward from the variable in the reverse order operations were applied.",
    questions: [
      {
        id: "math-two-step-equations-q1",
        type: "numeric",
        prompt: "Solve for x: 2x + 3 = 11",
        correctAnswer: 4,
        explanation: "Subtract 3 from both sides: 2x = 8. Divide by 2: x = 4.",
      },
      {
        id: "math-two-step-equations-q2",
        type: "numeric",
        prompt: "Solve for x: 3x - 5 = 16",
        correctAnswer: 7,
        explanation: "Add 5 to both sides: 3x = 21. Divide by 3: x = 7.",
      },
      {
        id: "math-two-step-equations-q3",
        type: "numeric",
        prompt: "Solve for x: x / 2 + 4 = 9",
        correctAnswer: 10,
        explanation: "Subtract 4 from both sides: x / 2 = 5. Multiply by 2: x = 10.",
      },
      {
        id: "math-two-step-equations-q4",
        type: "numeric",
        prompt: "Solve for x: -2x + 6 = 0",
        correctAnswer: 3,
        explanation: "Subtract 6 from both sides: -2x = -6. Divide by -2: x = 3.",
      },
      {
        id: "math-two-step-equations-q5",
        type: "multiple-choice",
        prompt: "When solving 4x - 7 = 13, what's the correct first step?",
        choices: [
          "Add 7 to both sides",
          "Subtract 7 from both sides",
          "Divide both sides by 4 first",
          "Add 13 to both sides",
        ],
        correctChoiceIndex: 0,
        explanation:
          "Undo addition/subtraction before multiplication/division. Adding 7 to both sides isolates the 4x term first.",
      },
      {
        id: "math-two-step-equations-q6",
        type: "numeric",
        prompt: "Solve for x: 5x + 2 = -13",
        correctAnswer: -3,
        explanation: "Subtract 2 from both sides: 5x = -15. Divide by 5: x = -3.",
      },
    ],
  },
  {
    id: "math-multi-step-equations",
    subject: "math",
    order: 6,
    title: "Multi-Step Equations",
    teachingBlurb:
      "Some equations have variables on both sides, or need distributing (multiplying through parentheses) before they can be solved. Simplify each side first, then move all variable terms to one side and all constants to the other.",
    questions: [
      {
        id: "math-multi-step-equations-q1",
        type: "numeric",
        prompt: "Solve for x: 3x + 4 = x + 10",
        correctAnswer: 3,
        explanation: "Subtract x from both sides: 2x + 4 = 10. Subtract 4: 2x = 6. Divide by 2: x = 3.",
      },
      {
        id: "math-multi-step-equations-q2",
        type: "numeric",
        prompt: "Solve for x: 5x - 2 = 2x + 13",
        correctAnswer: 5,
        explanation: "Subtract 2x from both sides: 3x - 2 = 13. Add 2: 3x = 15. Divide by 3: x = 5.",
      },
      {
        id: "math-multi-step-equations-q3",
        type: "numeric",
        prompt: "Solve for x: 2(x + 3) = 16",
        correctAnswer: 5,
        explanation: "Distribute: 2x + 6 = 16. Subtract 6: 2x = 10. Divide by 2: x = 5.",
      },
      {
        id: "math-multi-step-equations-q4",
        type: "numeric",
        prompt: "Solve for x: 4x - 3 = 2(x + 5)",
        correctAnswer: 6.5,
        tolerance: 0.01,
        explanation: "Distribute: 4x - 3 = 2x + 10. Subtract 2x: 2x - 3 = 10. Add 3: 2x = 13. Divide by 2: x = 6.5.",
      },
      {
        id: "math-multi-step-equations-q5",
        type: "multiple-choice",
        prompt: "When solving 3(x - 2) = 3x - 6, what's true about the solution?",
        choices: [
          "It has infinitely many solutions (it's an identity)",
          "It has no solution",
          "The only solution is x = 0",
          "The only solution is x = 6",
        ],
        correctChoiceIndex: 0,
        explanation:
          "Distributing the left side gives 3x - 6 = 3x - 6, which is true for every value of x — so any x works.",
      },
      {
        id: "math-multi-step-equations-q6",
        type: "numeric",
        prompt: "Solve for x: 7 - x = 2x + 1",
        correctAnswer: 2,
        explanation: "Add x to both sides: 7 = 3x + 1. Subtract 1: 6 = 3x. Divide by 3: x = 2.",
      },
    ],
  },
  {
    id: "math-coordinate-plane",
    subject: "math",
    order: 7,
    title: "The Coordinate Plane",
    teachingBlurb:
      "The coordinate plane is formed by a horizontal x-axis and a vertical y-axis meeting at the origin (0, 0). Every point is described by an ordered pair (x, y): x tells you how far to move left/right, y tells you how far to move up/down. The axes divide the plane into four quadrants.",
    questions: [
      {
        id: "math-coordinate-plane-q1",
        type: "multiple-choice",
        prompt: "In the ordered pair (3, -2), what does the -2 represent?",
        choices: [
          "Moving down 2 (the y-value)",
          "Moving left 2",
          "Moving up 2",
          "Moving right 2",
        ],
        correctChoiceIndex: 0,
        explanation: "The second number in an ordered pair is the y-value, which controls vertical movement — negative means down.",
      },
      {
        id: "math-coordinate-plane-q2",
        type: "multiple-choice",
        prompt: "Which quadrant contains the point (-4, 5)?",
        choices: ["Quadrant II", "Quadrant I", "Quadrant III", "Quadrant IV"],
        correctChoiceIndex: 0,
        explanation: "Negative x, positive y places a point in Quadrant II (top-left).",
      },
      {
        id: "math-coordinate-plane-q3",
        type: "multiple-choice",
        prompt: "The point (0, 6) lies on which axis?",
        choices: ["The y-axis", "The x-axis", "The origin", "It's not on any axis"],
        correctChoiceIndex: 0,
        explanation: "Any point with x = 0 lies on the y-axis, since it has no horizontal movement.",
      },
      {
        id: "math-coordinate-plane-q4",
        type: "numeric",
        prompt: "What is the x-coordinate of the point (7, -3)?",
        correctAnswer: 7,
        explanation: "The x-coordinate is always listed first in an ordered pair.",
      },
      {
        id: "math-coordinate-plane-q5",
        type: "multiple-choice",
        prompt: "Which quadrant contains points where both x and y are negative?",
        choices: ["Quadrant III", "Quadrant I", "Quadrant II", "Quadrant IV"],
        correctChoiceIndex: 0,
        explanation: "Quadrant III (bottom-left) is where both coordinates are negative.",
      },
      {
        id: "math-coordinate-plane-q6",
        type: "numeric",
        prompt: "A point is 4 units right and 5 units down from the origin. What is its y-coordinate?",
        correctAnswer: -5,
        explanation: "Moving down from the origin means a negative y-value, so the y-coordinate is -5.",
      },
    ],
  },
  {
    id: "math-graphing-linear-equations",
    subject: "math",
    order: 8,
    title: "Graphing Linear Equations",
    teachingBlurb:
      "A linear equation written as y = mx + b is in slope-intercept form. The slope m tells you how steep the line is (rise over run), and the y-intercept b tells you where the line crosses the y-axis, at the point (0, b).",
    questions: [
      {
        id: "math-graphing-linear-equations-q1",
        type: "multiple-choice",
        prompt: "In y = mx + b, what does m represent?",
        choices: ["The slope", "The y-intercept", "The x-intercept", "A constant with no meaning"],
        correctChoiceIndex: 0,
        explanation: "m is the coefficient of x and controls the line's steepness — the slope.",
      },
      {
        id: "math-graphing-linear-equations-q2",
        type: "multiple-choice",
        prompt: "In y = mx + b, what does b represent?",
        choices: ["The y-intercept", "The slope", "The x-value", "The origin"],
        correctChoiceIndex: 0,
        explanation: "b is the value of y when x = 0 — the point where the line crosses the y-axis.",
      },
      {
        id: "math-graphing-linear-equations-q3",
        type: "numeric",
        prompt: "For the line y = 2x + 3, what is the y-intercept?",
        correctAnswer: 3,
        explanation: "In y = mx + b form, the y-intercept is b, which is 3 here.",
      },
      {
        id: "math-graphing-linear-equations-q4",
        type: "numeric",
        prompt: "For the line y = -3x + 5, what is the slope?",
        correctAnswer: -3,
        explanation: "In y = mx + b form, the slope is m, which is -3 here.",
      },
      {
        id: "math-graphing-linear-equations-q5",
        type: "numeric",
        prompt: "Find y when x = 2 for the line y = 4x - 1.",
        correctAnswer: 7,
        explanation: "Substitute x = 2: y = 4(2) - 1 = 8 - 1 = 7.",
      },
      {
        id: "math-graphing-linear-equations-q6",
        type: "multiple-choice",
        prompt: "A line has a slope of 0. What does its graph look like?",
        choices: ["A horizontal line", "A vertical line", "A line through the origin only", "It has no graph"],
        correctChoiceIndex: 0,
        explanation: "A slope of 0 means y never changes as x changes, which draws a flat, horizontal line.",
      },
    ],
  },
];
