import type { Lesson } from "@/lib/types";

export const scienceLessons: Lesson[] = [
  {
    id: "science-states-of-matter",
    subject: "science",
    order: 1,
    title: "States of Matter",
    teachingBlurb:
      "Matter is anything that has mass and takes up space, and it exists in different states depending on how tightly its particles are packed and how much energy they have. In a solid, particles vibrate in a fixed position; in a liquid, they're close but can flow past each other; in a gas, they're spread out and move freely. Adding or removing heat energy can change matter from one state to another.",
    questions: [
      {
        id: "science-states-of-matter-q1",
        type: "multiple-choice",
        prompt: "In a solid, the particles are...",
        choices: [
          "Tightly packed and vibrating in place",
          "Free to flow past each other but still close together",
          "Spread far apart and moving fast",
          "Completely motionless, with zero energy",
        ],
        correctChoiceIndex: 0,
        explanation: "Solid particles have a fixed arrangement — they vibrate but don't change position, which is why solids hold their shape.",
      },
      {
        id: "science-states-of-matter-q2",
        type: "multiple-choice",
        prompt: "What is the process called when a liquid changes to a gas?",
        choices: ["Evaporation (vaporization)", "Condensation", "Freezing", "Sublimation"],
        correctChoiceIndex: 0,
        explanation: "Evaporation (or vaporization when it happens throughout the liquid, as in boiling) is liquid turning to gas.",
      },
      {
        id: "science-states-of-matter-q3",
        type: "multiple-choice",
        prompt: "What is it called when a solid changes directly into a gas, skipping the liquid phase?",
        choices: ["Sublimation", "Deposition", "Melting", "Boiling"],
        correctChoiceIndex: 0,
        explanation: "Sublimation skips the liquid state entirely — dry ice (solid CO₂) turning to fog is a common example.",
      },
      {
        id: "science-states-of-matter-q4",
        type: "multiple-choice",
        prompt: "As you add heat energy to ice at 0°C, what happens to its temperature while it's melting?",
        choices: [
          "It stays the same until melting is complete",
          "It rises steadily",
          "It drops",
          "It doubles instantly",
        ],
        correctChoiceIndex: 0,
        explanation: "During a phase change, added energy goes into breaking the bonds between particles rather than raising the temperature, so the temperature holds steady until the change is complete.",
      },
      {
        id: "science-states-of-matter-q5",
        type: "multiple-choice",
        prompt: "Which state of matter takes both the shape AND the volume of its container?",
        choices: ["Gas", "Solid", "Liquid", "Plasma"],
        correctChoiceIndex: 0,
        explanation: "A gas expands to completely fill whatever container it's in, taking on both its shape and volume. A liquid takes the shape but keeps a fixed volume.",
      },
      {
        id: "science-states-of-matter-q6",
        type: "multiple-choice",
        prompt: "Condensation is the change of state from...",
        choices: ["Gas to liquid", "Liquid to gas", "Solid to liquid", "Liquid to solid"],
        correctChoiceIndex: 0,
        explanation: "Condensation happens when a gas loses energy and its particles come together into a liquid — like water droplets forming on a cold glass.",
      },
    ],
  },
  {
    id: "science-physical-chemical-changes",
    subject: "science",
    order: 2,
    title: "Physical vs. Chemical Changes",
    teachingBlurb:
      "A physical change alters how matter looks (its shape, size, or state) without turning it into a new substance — the material can often be changed back. A chemical change produces one or more new substances with different properties, usually shown by clues like gas bubbles, a color change, a new smell, or a temperature change that isn't just from mixing.",
    questions: [
      {
        id: "science-physical-chemical-changes-q1",
        type: "multiple-choice",
        prompt: "Which is an example of a physical change?",
        choices: ["Tearing a piece of paper", "Burning a piece of paper", "A nail rusting", "Baking a cake"],
        correctChoiceIndex: 0,
        explanation: "Tearing paper only changes its shape — it's still the same paper. Burning, rusting, and baking all create new substances.",
      },
      {
        id: "science-physical-chemical-changes-q2",
        type: "multiple-choice",
        prompt: "Which is a sign that a chemical change has occurred?",
        choices: [
          "A new substance forms with new properties, like gas bubbles or a color change",
          "The object changes shape",
          "The object changes size",
          "The object gets colder from being touched",
        ],
        correctChoiceIndex: 0,
        explanation: "Chemical changes create new substances, often signaled by gas production, color change, precipitate formation, or an unexpected temperature change.",
      },
      {
        id: "science-physical-chemical-changes-q3",
        type: "multiple-choice",
        prompt: "Dissolving sugar in water is what type of change?",
        choices: [
          "Physical change — the sugar molecules are still sugar",
          "Chemical change — a new substance is formed",
          "Neither, nothing actually happened",
          "Both a physical and chemical change equally",
        ],
        correctChoiceIndex: 0,
        explanation: "The sugar spreads out among the water molecules but doesn't change chemically — evaporating the water would leave the same sugar behind.",
      },
      {
        id: "science-physical-chemical-changes-q4",
        type: "multiple-choice",
        prompt: "Which of these is a chemical change?",
        choices: ["Iron rusting into iron oxide", "Melting butter", "Crushing a soda can", "Cutting a rope"],
        correctChoiceIndex: 0,
        explanation: "Rusting combines iron with oxygen to form a new substance, iron oxide, with different properties than the original metal.",
      },
      {
        id: "science-physical-chemical-changes-q5",
        type: "multiple-choice",
        prompt: "Boiling water is a ___ change, because no new substance is formed.",
        choices: ["physical", "chemical", "nuclear", "biological"],
        correctChoiceIndex: 0,
        explanation: "Boiling only changes water from liquid to gas — it's still H₂O, so it's a physical change.",
      },
      {
        id: "science-physical-chemical-changes-q6",
        type: "multiple-choice",
        prompt: "Which observation is the strongest evidence of a chemical reaction?",
        choices: [
          "Bubbles forming along with a temperature change and a new odor",
          "The liquid became slightly warmer after stirring",
          "A solid was broken into smaller pieces",
          "The color got more intense when more was added",
        ],
        correctChoiceIndex: 0,
        explanation: "Multiple simultaneous signs — gas production, a temperature shift not explained by mixing, and a new smell — together strongly suggest a new substance formed.",
      },
    ],
  },
  {
    id: "science-atoms-elements",
    subject: "science",
    order: 3,
    title: "Atoms, Elements & the Periodic Table",
    teachingBlurb:
      "All matter is made of atoms, the smallest unit of an element that keeps that element's properties. Atoms have a nucleus of protons (positive) and neutrons (neutral), surrounded by electrons (negative). The periodic table arranges elements so that rows (periods) reflect the number of electron shells, and columns (groups) share similar chemical properties.",
    questions: [
      {
        id: "science-atoms-elements-q1",
        type: "multiple-choice",
        prompt: "What is the smallest unit of an element that still has that element's properties?",
        choices: ["An atom", "A molecule", "A compound", "A cell"],
        correctChoiceIndex: 0,
        explanation: "An atom is the basic building block of an element — split it apart and it's no longer that element.",
      },
      {
        id: "science-atoms-elements-q2",
        type: "multiple-choice",
        prompt: "What do the rows (periods) of the periodic table generally represent?",
        choices: [
          "Elements with the same number of electron shells",
          "Elements with the same number of protons",
          "Elements with identical mass",
          "Elements listed in alphabetical order",
        ],
        correctChoiceIndex: 0,
        explanation: "Each period corresponds to a new electron shell being filled, so elements in the same row have the same number of shells.",
      },
      {
        id: "science-atoms-elements-q3",
        type: "multiple-choice",
        prompt: "What do elements in the same column (group) of the periodic table share?",
        choices: [
          "Similar chemical properties, from similar outer-shell electrons",
          "The exact same atomic mass",
          "The exact same number of neutrons",
          "The exact same color",
        ],
        correctChoiceIndex: 0,
        explanation: "Elements in a group have the same number of electrons in their outermost shell, which largely determines how they react chemically.",
      },
      {
        id: "science-atoms-elements-q4",
        type: "numeric",
        prompt: "An atom of carbon has 6 protons. In a neutral atom, how many electrons does it have?",
        correctAnswer: 6,
        explanation: "A neutral atom has no overall charge, so its number of electrons always equals its number of protons.",
      },
      {
        id: "science-atoms-elements-q5",
        type: "multiple-choice",
        prompt: "Which particle has a negative electric charge?",
        choices: ["Electron", "Proton", "Neutron", "Nucleus"],
        correctChoiceIndex: 0,
        explanation: "Electrons are negatively charged; protons are positive and neutrons have no charge.",
      },
      {
        id: "science-atoms-elements-q6",
        type: "multiple-choice",
        prompt: "Where are protons and neutrons located in an atom?",
        choices: ["In the nucleus", "Orbiting the nucleus", "Outside the atom entirely", "In the electron cloud"],
        correctChoiceIndex: 0,
        explanation: "The nucleus, at the atom's center, holds the protons and neutrons; electrons occupy the space around it.",
      },
    ],
  },
  {
    id: "science-energy-forms",
    subject: "science",
    order: 4,
    title: "Energy Forms & Conservation",
    teachingBlurb:
      "Energy exists in many forms — kinetic (motion), potential (stored, like height or a stretched spring), thermal, chemical, and more. The law of conservation of energy says total energy in a closed system never disappears; it only transforms from one form to another, such as potential energy converting to kinetic energy as an object falls.",
    questions: [
      {
        id: "science-energy-forms-q1",
        type: "multiple-choice",
        prompt: "The law of conservation of energy states that energy...",
        choices: [
          "Cannot be created or destroyed, only transformed from one form to another",
          "Is always lost permanently over time",
          "Can be created but never destroyed",
          "Only exists as heat",
        ],
        correctChoiceIndex: 0,
        explanation: "Total energy in a closed system stays constant — it changes form (like potential to kinetic) but the total amount doesn't change.",
      },
      {
        id: "science-energy-forms-q2",
        type: "multiple-choice",
        prompt: "A ball held above the ground has mostly which type of energy?",
        choices: ["Gravitational potential energy", "Kinetic energy", "Thermal energy", "Sound energy"],
        correctChoiceIndex: 0,
        explanation: "Height above the ground stores energy due to gravity — this is gravitational potential energy, which depends on height and mass.",
      },
      {
        id: "science-energy-forms-q3",
        type: "multiple-choice",
        prompt: "As the ball falls, its potential energy converts mostly into...",
        choices: ["Kinetic energy", "Chemical energy", "Nuclear energy", "Electrical energy"],
        correctChoiceIndex: 0,
        explanation: "Falling means losing height (less potential energy) while speed increases (more kinetic energy) — the energy transforms from one form to the other.",
      },
      {
        id: "science-energy-forms-q4",
        type: "multiple-choice",
        prompt: "Which is an example of kinetic energy?",
        choices: [
          "A car driving down the highway",
          "A stretched rubber band before it's released",
          "A book sitting on a shelf",
          "A fully charged battery",
        ],
        correctChoiceIndex: 0,
        explanation: "Kinetic energy is the energy of motion — a moving car has it. The other examples are all forms of stored (potential or chemical) energy.",
      },
      {
        id: "science-energy-forms-q5",
        type: "multiple-choice",
        prompt: "In a swinging pendulum (ignoring friction), where is its kinetic energy at its maximum?",
        choices: [
          "At the lowest point of the swing",
          "At the highest point of the swing",
          "It stays constant throughout",
          "Only at the very start",
        ],
        correctChoiceIndex: 0,
        explanation: "At the lowest point, the pendulum has lost the most height (least potential energy) and moves fastest, so kinetic energy peaks there.",
      },
      {
        id: "science-energy-forms-q6",
        type: "numeric",
        prompt: "A system starts with 100 J of potential energy and loses 20 J to friction (heat) as it moves. Assuming total energy is conserved, how many joules of kinetic energy does it end up with?",
        correctAnswer: 80,
        unit: "J",
        explanation: "Total energy stays at 100 J. If 20 J becomes heat from friction, the remaining 80 J becomes kinetic energy.",
      },
    ],
  },
  {
    id: "science-newtons-laws",
    subject: "science",
    order: 5,
    title: "Newton's Laws of Motion",
    teachingBlurb:
      "Isaac Newton described three laws that explain how forces affect motion. First Law: an object keeps its state of motion unless an unbalanced force acts on it. Second Law: force equals mass times acceleration (F = m × a). Third Law: every action force has an equal and opposite reaction force.",
    questions: [
      {
        id: "science-newtons-laws-q1",
        type: "multiple-choice",
        prompt: "Newton's First Law says an object at rest stays at rest, and an object in motion stays in motion, unless acted on by...",
        choices: ["An unbalanced (net) force", "Gravity only", "The passage of time", "Its own energy running out"],
        correctChoiceIndex: 0,
        explanation: "This is the law of inertia — motion only changes when a net (unbalanced) force is applied.",
      },
      {
        id: "science-newtons-laws-q2",
        type: "multiple-choice",
        prompt: "Newton's Second Law is often written as the formula:",
        choices: ["F = m × a", "E = m × c^2", "F = m / a", "a = F + m"],
        correctChoiceIndex: 0,
        explanation: "Force equals mass times acceleration — a larger force or smaller mass produces greater acceleration.",
      },
      {
        id: "science-newtons-laws-q3",
        type: "numeric",
        prompt: "Using F = m × a, find the force (in newtons) needed to accelerate a 10 kg object at 3 m/s^2.",
        correctAnswer: 30,
        unit: "N",
        explanation: "F = m × a = 10 kg × 3 m/s^2 = 30 N.",
      },
      {
        id: "science-newtons-laws-q4",
        type: "multiple-choice",
        prompt: "Newton's Third Law states that for every action there is...",
        choices: ["An equal and opposite reaction", "A stronger reaction", "No reaction at all", "A delayed reaction"],
        correctChoiceIndex: 0,
        explanation: "Forces always come in pairs: when object A pushes on object B, B pushes back on A with equal force in the opposite direction.",
      },
      {
        id: "science-newtons-laws-q5",
        type: "multiple-choice",
        prompt: "A rocket launches upward by pushing exhaust gas downward. This is best explained by...",
        choices: [
          "Newton's Third Law (action-reaction pairs)",
          "Newton's First Law",
          "The law of conservation of mass",
          "Gravity alone",
        ],
        correctChoiceIndex: 0,
        explanation: "The rocket pushes gas down (action); the gas pushes the rocket up with equal force (reaction) — a direct example of the Third Law.",
      },
      {
        id: "science-newtons-laws-q6",
        type: "numeric",
        prompt: "A 5 kg object accelerates at 4 m/s^2. What net force (in newtons) is acting on it?",
        correctAnswer: 20,
        unit: "N",
        explanation: "F = m × a = 5 kg × 4 m/s^2 = 20 N.",
      },
    ],
  },
  {
    id: "science-speed-velocity",
    subject: "science",
    order: 6,
    title: "Speed, Velocity & Motion",
    teachingBlurb:
      "Speed measures how fast something moves (distance ÷ time), while velocity adds a direction to that speed. On a distance-time graph, the steepness (slope) of the line shows speed — a steeper line means faster motion, and a flat line means the object isn't moving.",
    questions: [
      {
        id: "science-speed-velocity-q1",
        type: "multiple-choice",
        prompt: "What is the main difference between speed and velocity?",
        choices: [
          "Velocity includes direction, speed does not",
          "Speed includes direction, velocity does not",
          "They mean exactly the same thing",
          "Velocity is always faster than speed",
        ],
        correctChoiceIndex: 0,
        explanation: "Speed is just a number (like 50 km/h); velocity is that number plus a direction (like 50 km/h north).",
      },
      {
        id: "science-speed-velocity-q2",
        type: "numeric",
        prompt: "A car travels 150 km in 3 hours. What is its average speed in km/h?",
        correctAnswer: 50,
        unit: "km/h",
        explanation: "Speed = distance ÷ time = 150 km ÷ 3 h = 50 km/h.",
      },
      {
        id: "science-speed-velocity-q3",
        type: "numeric",
        prompt: "A runner covers 400 meters in 50 seconds. What is their average speed in m/s?",
        correctAnswer: 8,
        unit: "m/s",
        explanation: "Speed = distance ÷ time = 400 m ÷ 50 s = 8 m/s.",
      },
      {
        id: "science-speed-velocity-q4",
        type: "multiple-choice",
        prompt: "On a distance-time graph, a steeper line means...",
        choices: ["A faster speed", "A slower speed", "No motion at all", "The object has stopped"],
        correctChoiceIndex: 0,
        explanation: "A steeper slope means distance is changing faster over time, which is a higher speed.",
      },
      {
        id: "science-speed-velocity-q5",
        type: "multiple-choice",
        prompt: "A flat, horizontal line on a distance-time graph means the object is...",
        choices: ["At rest (not moving)", "Moving at a constant fast speed", "Accelerating", "Moving backward"],
        correctChoiceIndex: 0,
        explanation: "A flat line means distance isn't changing as time passes, which means the object is standing still.",
      },
      {
        id: "science-speed-velocity-q6",
        type: "numeric",
        prompt: "If you travel 60 miles in 1.5 hours, what is your average speed in mph?",
        correctAnswer: 40,
        unit: "mph",
        explanation: "Speed = distance ÷ time = 60 miles ÷ 1.5 h = 40 mph.",
      },
    ],
  },
  {
    id: "science-cells-and-energy",
    subject: "science",
    order: 7,
    title: "Cells and Energy",
    teachingBlurb:
      "The cell is the basic unit of life. Plant cells use photosynthesis in their chloroplasts to turn light energy, water, and carbon dioxide into glucose (sugar) and oxygen. Nearly all cells use cellular respiration in their mitochondria to break glucose back down with oxygen, releasing usable energy (ATP) that powers the cell.",
    questions: [
      {
        id: "science-cells-and-energy-q1",
        type: "multiple-choice",
        prompt: "What is the basic unit of structure and function in living things?",
        choices: ["The cell", "The atom", "The organ", "The tissue"],
        correctChoiceIndex: 0,
        explanation: "Every living thing is made of one or more cells — the smallest unit that can be considered alive.",
      },
      {
        id: "science-cells-and-energy-q2",
        type: "multiple-choice",
        prompt: "During photosynthesis, plants convert light energy, water, and carbon dioxide into...",
        choices: [
          "Glucose (sugar) and oxygen",
          "Protein and nitrogen",
          "Carbon dioxide and water only",
          "DNA and RNA",
        ],
        correctChoiceIndex: 0,
        explanation: "Photosynthesis captures light energy to build glucose from CO₂ and water, releasing oxygen as a byproduct.",
      },
      {
        id: "science-cells-and-energy-q3",
        type: "multiple-choice",
        prompt: "Where in the plant cell does photosynthesis mainly take place?",
        choices: ["Chloroplast", "Mitochondria", "Nucleus", "Cell wall"],
        correctChoiceIndex: 0,
        explanation: "Chloroplasts contain chlorophyll, the pigment that captures light energy for photosynthesis.",
      },
      {
        id: "science-cells-and-energy-q4",
        type: "multiple-choice",
        prompt: "Cellular respiration is best described as...",
        choices: [
          "Breaking down glucose with oxygen to release usable energy (ATP)",
          "Making glucose using sunlight",
          "Absorbing water through plant roots",
          "Splitting water into hydrogen and oxygen",
        ],
        correctChoiceIndex: 0,
        explanation: "Respiration is essentially the reverse of photosynthesis — it releases the energy stored in glucose so the cell can use it.",
      },
      {
        id: "science-cells-and-energy-q5",
        type: "multiple-choice",
        prompt: "Which organelle is known as the 'powerhouse of the cell,' where respiration mainly occurs?",
        choices: ["Mitochondria", "Chloroplast", "Nucleus", "Ribosome"],
        correctChoiceIndex: 0,
        explanation: "Mitochondria convert glucose and oxygen into usable energy (ATP) for the cell.",
      },
      {
        id: "science-cells-and-energy-q6",
        type: "multiple-choice",
        prompt: "Photosynthesis and cellular respiration are connected because...",
        choices: [
          "The products of one (glucose, oxygen) are used as the reactants in the other",
          "They both happen only in animal cells",
          "They are completely unrelated processes",
          "Respiration only happens in plants",
        ],
        correctChoiceIndex: 0,
        explanation: "Photosynthesis makes glucose and oxygen; respiration consumes glucose and oxygen to release energy — each process feeds the other.",
      },
    ],
  },
];
