import type { Lesson } from "@/lib/types";

export const technologyLessons: Lesson[] = [
  {
    id: "technology-computational-thinking",
    subject: "technology",
    order: 1,
    title: "What Is Computational Thinking?",
    teachingBlurb:
      "Computational thinking is a way of solving problems that programmers use, built on four skills: decomposition (breaking a big problem into smaller pieces), pattern recognition (spotting similarities between problems), abstraction (ignoring details that don't matter and focusing on what does), and algorithm design (writing clear step-by-step instructions). These skills work for far more than just coding.",
    questions: [
      {
        id: "technology-computational-thinking-q1",
        type: "multiple-choice",
        prompt: "Breaking a big problem into smaller, more manageable parts is called...",
        choices: ["Decomposition", "Abstraction", "Pattern recognition", "Debugging"],
        correctChoiceIndex: 0,
        explanation: "Decomposition means splitting a large problem into smaller sub-problems that are each easier to solve on their own.",
      },
      {
        id: "technology-computational-thinking-q2",
        type: "multiple-choice",
        prompt: "Noticing that several problems share similar features or repeat in similar ways is called...",
        choices: ["Pattern recognition", "Decomposition", "Compilation", "Iteration"],
        correctChoiceIndex: 0,
        explanation: "Pattern recognition lets you reuse a known solution approach when you spot a familiar structure in a new problem.",
      },
      {
        id: "technology-computational-thinking-q3",
        type: "multiple-choice",
        prompt: "Focusing only on the important details of a problem and ignoring irrelevant ones is called...",
        choices: ["Abstraction", "Recursion", "Sequencing", "Syntax"],
        correctChoiceIndex: 0,
        explanation: "Abstraction hides unnecessary complexity so you can concentrate on the parts of the problem that actually matter.",
      },
      {
        id: "technology-computational-thinking-q4",
        type: "multiple-choice",
        prompt: "A precise, step-by-step set of instructions to solve a problem is called an...",
        choices: ["Algorithm", "Interface", "Variable", "Loop"],
        correctChoiceIndex: 0,
        explanation: "An algorithm is an ordered sequence of steps that, if followed exactly, solves a problem or completes a task.",
      },
      {
        id: "technology-computational-thinking-q5",
        type: "multiple-choice",
        prompt: "Which is the BEST example of decomposition?",
        choices: [
          "Breaking 'plan a birthday party' into smaller tasks like guest list, food, decorations, and invitations",
          "Guessing randomly until something works",
          "Memorizing the whole plan without writing anything down",
          "Making the plan as vague as possible",
        ],
        correctChoiceIndex: 0,
        explanation: "Splitting a big task into clear sub-tasks that can each be tackled individually is exactly what decomposition means.",
      },
      {
        id: "technology-computational-thinking-q6",
        type: "multiple-choice",
        prompt: "Why do computer scientists use abstraction?",
        choices: [
          "To hide unnecessary complexity so they can focus on what matters for the problem",
          "To make programs slower on purpose",
          "To add more unnecessary steps to an algorithm",
          "To avoid using variables entirely",
        ],
        correctChoiceIndex: 0,
        explanation: "Abstraction lets you work with a simplified model (like 'press the gas pedal to accelerate') without needing to think about every underlying detail.",
      },
    ],
  },
  {
    id: "technology-algorithms-sequences",
    subject: "technology",
    order: 2,
    title: "Algorithms & Sequences",
    teachingBlurb:
      "A sequence is a series of instructions carried out one after another, in the exact order they're written — computers don't skip around or guess. Because of this, the order of steps in an algorithm matters enormously: swapping two steps can produce a completely different, or broken, result. Pseudocode is a way of writing algorithms in plain, structured language without tying them to one programming language.",
    questions: [
      {
        id: "technology-algorithms-sequences-q1",
        type: "multiple-choice",
        prompt: "In a sequence, instructions are carried out...",
        choices: [
          "One after another, in the order they're written",
          "In a random order each time",
          "All at exactly the same instant",
          "Only the last instruction runs",
        ],
        correctChoiceIndex: 0,
        explanation: "A sequence is fundamentally about order — each step runs in turn, from first to last.",
      },
      {
        id: "technology-algorithms-sequences-q2",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET total = 0\nSET total = total + 5\nSET total = total * 2\nWhat is the value of total after this sequence runs?",
        correctAnswer: 10,
        explanation: "total starts at 0, becomes 0 + 5 = 5, then becomes 5 * 2 = 10.",
      },
      {
        id: "technology-algorithms-sequences-q3",
        type: "multiple-choice",
        prompt: "You want a robot to make a peanut butter sandwich. Which step order is correct?",
        choices: [
          "Get bread, spread peanut butter, put slices together",
          "Spread peanut butter, get bread, put slices together",
          "Put slices together, get bread, spread peanut butter",
          "Eat the sandwich, get bread, spread peanut butter",
        ],
        correctChoiceIndex: 0,
        explanation: "Each step depends on the one before it being done — you need the bread out before you can spread on it, and both slices spread before combining them.",
      },
      {
        id: "technology-algorithms-sequences-q4",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET x = 3\nSET y = x + 4\nSET x = y - 1\nWhat is the final value of x?",
        correctAnswer: 6,
        explanation: "x starts at 3. y becomes 3 + 4 = 7. Then x becomes y - 1 = 7 - 1 = 6.",
      },
      {
        id: "technology-algorithms-sequences-q5",
        type: "multiple-choice",
        prompt: "Why does the ORDER of steps in an algorithm matter?",
        choices: [
          "Because swapping steps can produce a completely different (or broken) result",
          "Order never actually matters in programming",
          "Computers automatically fix any wrong order",
          "Only the very first step in a program matters",
        ],
        correctChoiceIndex: 0,
        explanation: "Since each step often depends on the result of the one before it, changing the order can change — or break — the outcome entirely.",
      },
      {
        id: "technology-algorithms-sequences-q6",
        type: "multiple-choice",
        prompt: "What do we call an algorithm written in a mix of plain language and code-like structure, not tied to one programming language?",
        choices: ["Pseudocode", "Syntax", "A compiler", "Binary"],
        correctChoiceIndex: 0,
        explanation: "Pseudocode lets programmers plan an algorithm's logic clearly before writing it in any specific programming language.",
      },
    ],
  },
  {
    id: "technology-variables-data",
    subject: "technology",
    order: 3,
    title: "Variables & Data",
    teachingBlurb:
      "A variable is a named container that stores a value a program can use and change while it runs. Data comes in different types — numbers, strings (text), and booleans (true/false) are the most common — and giving variables clear, descriptive names makes code easier for people to read and understand.",
    questions: [
      {
        id: "technology-variables-data-q1",
        type: "multiple-choice",
        prompt: "A variable is best described as...",
        choices: [
          "A named container that stores a value which can change",
          "A fixed value that never changes",
          "A type of loop",
          "An error in the code",
        ],
        correctChoiceIndex: 0,
        explanation: "Variables hold data that the program can read and update as it runs — that's what makes them 'variable.'",
      },
      {
        id: "technology-variables-data-q2",
        type: "multiple-choice",
        prompt: "Which of these would be stored as a 'boolean' data type?",
        choices: ["True or False (e.g. isGameOver)", "The number 42", "The text 'hello'", "A list of scores"],
        correctChoiceIndex: 0,
        explanation: "A boolean can only hold one of two values: true or false — perfect for yes/no states like whether the game has ended.",
      },
      {
        id: "technology-variables-data-q3",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET score = 10\nSET score = score + 5\nSET score = score + 5\nWhat is the final value of score?",
        correctAnswer: 20,
        explanation: "score starts at 10, then 10 + 5 = 15, then 15 + 5 = 20.",
      },
      {
        id: "technology-variables-data-q4",
        type: "multiple-choice",
        prompt: "Which variable name is the MOST descriptive for storing a player's number of lives?",
        choices: ["playerLives", "x", "thing1", "temp"],
        correctChoiceIndex: 0,
        explanation: "Descriptive variable names like playerLives make code much easier to read and debug than vague names like x or temp.",
      },
      {
        id: "technology-variables-data-q5",
        type: "multiple-choice",
        prompt: "What data type would best store someone's name, like 'Maria'?",
        choices: ["String (text)", "Integer (number)", "Boolean", "Array only"],
        correctChoiceIndex: 0,
        explanation: "Text data — letters and words — is stored using the string data type.",
      },
      {
        id: "technology-variables-data-q6",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET a = 4\nSET b = 7\nSET c = a * b\nWhat is the value of c?",
        correctAnswer: 28,
        explanation: "c = a * b = 4 * 7 = 28.",
      },
    ],
  },
  {
    id: "technology-conditionals",
    subject: "technology",
    order: 4,
    title: "Conditionals — Making Decisions",
    teachingBlurb:
      "Conditionals let a program make decisions using IF statements. An IF checks whether a condition is true or false — if true, one block of code runs; if there's an ELSE, its block runs instead when the condition is false. Chaining ELSE IF lets a program check several conditions in order until one matches.",
    questions: [
      {
        id: "technology-conditionals-q1",
        type: "multiple-choice",
        prompt: "Trace this pseudocode:\nIF score >= 60 THEN\n  PRINT \"Pass\"\nELSE\n  PRINT \"Fail\"\nEND IF\nIf score = 45, what gets printed?",
        choices: ["Fail", "Pass", "Nothing", "Error"],
        correctChoiceIndex: 0,
        explanation: "45 is not greater than or equal to 60, so the condition is false and the ELSE branch runs, printing 'Fail'.",
      },
      {
        id: "technology-conditionals-q2",
        type: "multiple-choice",
        prompt: "Using the same pseudocode as above, if score = 60, what gets printed?",
        choices: ["Pass", "Fail", "Nothing", "Error"],
        correctChoiceIndex: 0,
        explanation: "60 >= 60 is true, since >= includes equal to, so the IF branch runs, printing 'Pass'.",
      },
      {
        id: "technology-conditionals-q3",
        type: "multiple-choice",
        prompt: "An IF statement's condition must evaluate to...",
        choices: ["True or False", "A number only", "Text only", "A loop"],
        correctChoiceIndex: 0,
        explanation: "Conditions are boolean expressions — they always resolve to true or false, which decides which branch runs.",
      },
      {
        id: "technology-conditionals-q4",
        type: "multiple-choice",
        prompt: "Trace this pseudocode:\nIF temperature > 90 THEN\n  PRINT \"Hot\"\nELSE IF temperature > 60 THEN\n  PRINT \"Mild\"\nELSE\n  PRINT \"Cold\"\nEND IF\nIf temperature = 75, what prints?",
        choices: ["Mild", "Hot", "Cold", "Nothing"],
        correctChoiceIndex: 0,
        explanation: "75 is not greater than 90, so the first condition fails. 75 > 60 is true, so 'Mild' prints.",
      },
      {
        id: "technology-conditionals-q5",
        type: "multiple-choice",
        prompt: "What is the purpose of the ELSE branch in an if/else statement?",
        choices: [
          "It runs only when the IF condition is false",
          "It always runs no matter what",
          "It runs before the IF condition is even checked",
          "It deletes the variable being checked",
        ],
        correctChoiceIndex: 0,
        explanation: "ELSE is the fallback branch — it only executes when none of the preceding conditions were true.",
      },
      {
        id: "technology-conditionals-q6",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET x = 8\nIF x > 5 THEN\n  SET x = x + 10\nELSE\n  SET x = x - 10\nEND IF\nWhat is the final value of x?",
        correctAnswer: 18,
        explanation: "8 > 5 is true, so the IF branch runs: x = 8 + 10 = 18.",
      },
    ],
  },
  {
    id: "technology-loops",
    subject: "technology",
    order: 5,
    title: "Loops — Repeating Actions",
    teachingBlurb:
      "A loop repeats a block of instructions without making you rewrite them. A FOR loop repeats a fixed, known number of times. A WHILE loop keeps repeating as long as its condition stays true — including possibly zero times if the condition starts false. If a WHILE loop's condition never becomes false, it becomes an infinite loop that never stops running.",
    questions: [
      {
        id: "technology-loops-q1",
        type: "multiple-choice",
        prompt: "A loop is used when you want to...",
        choices: [
          "Repeat a set of instructions multiple times without rewriting them",
          "Run a set of instructions exactly once",
          "Make a decision between two options",
          "Store a single value",
        ],
        correctChoiceIndex: 0,
        explanation: "Loops exist to avoid repeating the same code over and over — they run a block of instructions multiple times automatically.",
      },
      {
        id: "technology-loops-q2",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET total = 0\nFOR i FROM 1 TO 4\n  SET total = total + i\nEND FOR\nWhat is total after the loop finishes?",
        correctAnswer: 10,
        explanation: "The loop adds 1 + 2 + 3 + 4 to total, one step at a time: 0+1=1, 1+2=3, 3+3=6, 6+4=10.",
      },
      {
        id: "technology-loops-q3",
        type: "multiple-choice",
        prompt: "A loop that keeps repeating as long as a condition is true, and might never run at all if the condition starts false, is called a...",
        choices: ["WHILE loop", "FOR loop with a fixed count", "Sequence", "Conditional"],
        correctChoiceIndex: 0,
        explanation: "A WHILE loop checks its condition before each pass, so if the condition is false to begin with, the loop body never runs.",
      },
      {
        id: "technology-loops-q4",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET count = 0\nFOR i FROM 1 TO 5\n  SET count = count + 2\nEND FOR\nWhat is count after this loop?",
        correctAnswer: 10,
        explanation: "The loop body runs 5 times, adding 2 each time: 5 × 2 = 10.",
      },
      {
        id: "technology-loops-q5",
        type: "multiple-choice",
        prompt: "What is the danger of writing a WHILE loop whose condition never becomes false?",
        choices: [
          "An infinite loop that never stops running",
          "The program runs faster than normal",
          "The variable inside disappears",
          "Nothing — it's always perfectly safe",
        ],
        correctChoiceIndex: 0,
        explanation: "If the condition can never become false, the loop keeps repeating forever, freezing or crashing the program.",
      },
      {
        id: "technology-loops-q6",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET n = 1\nWHILE n < 20\n  SET n = n * 2\nEND WHILE\nWhat is the final value of n?",
        correctAnswer: 32,
        explanation: "n doubles each pass while it's under 20: 1→2→4→8→16→32. At n=32, 32 < 20 is false, so the loop stops with n = 32.",
      },
    ],
  },
  {
    id: "technology-loops-and-conditionals",
    subject: "technology",
    order: 6,
    title: "Combining Loops & Conditionals",
    teachingBlurb:
      "Loops and conditionals become much more powerful together: a loop repeats an action, and a conditional inside it decides whether that action should apply on each pass. This combination is how programs process lists of data — checking every item and reacting differently depending on what each one is.",
    questions: [
      {
        id: "technology-loops-and-conditionals-q1",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET evenSum = 0\nFOR i FROM 1 TO 6\n  IF i MOD 2 == 0 THEN\n    SET evenSum = evenSum + i\n  END IF\nEND FOR\nWhat is evenSum after this runs?",
        correctAnswer: 12,
        explanation: "Only even values of i add to evenSum: 2 + 4 + 6 = 12.",
      },
      {
        id: "technology-loops-and-conditionals-q2",
        type: "multiple-choice",
        prompt: "In the pseudocode above, what does 'i MOD 2 == 0' check for?",
        choices: ["Whether i is an even number", "Whether i is odd", "Whether i equals 2", "Whether i is greater than 2"],
        correctChoiceIndex: 0,
        explanation: "MOD gives the remainder after division. A number has remainder 0 when divided by 2 exactly when it's even.",
      },
      {
        id: "technology-loops-and-conditionals-q3",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET count = 0\nFOR i FROM 1 TO 10\n  IF i > 7 THEN\n    SET count = count + 1\n  END IF\nEND FOR\nWhat is count after this loop?",
        correctAnswer: 3,
        explanation: "Only i = 8, 9, and 10 are greater than 7, so count increases 3 times.",
      },
      {
        id: "technology-loops-and-conditionals-q4",
        type: "multiple-choice",
        prompt: "Why combine loops with conditionals?",
        choices: [
          "To repeat an action but only apply it when a specific condition is met each time",
          "Loops and conditionals can never actually be combined",
          "To make code run without using any logic",
          "To remove the need for variables",
        ],
        correctChoiceIndex: 0,
        explanation: "Combining them lets a program repeat a check across many values and react differently depending on each one — a very common pattern.",
      },
      {
        id: "technology-loops-and-conditionals-q5",
        type: "numeric",
        prompt: "Trace this pseudocode:\nSET total = 0\nFOR i FROM 1 TO 5\n  IF i == 3 THEN\n    SET total = total + 100\n  ELSE\n    SET total = total + 1\n  END IF\nEND FOR\nWhat is total after this loop?",
        correctAnswer: 104,
        explanation: "i=1→+1(1), i=2→+1(2), i=3→+100(102), i=4→+1(103), i=5→+1(104). Final total is 104.",
      },
      {
        id: "technology-loops-and-conditionals-q6",
        type: "multiple-choice",
        prompt: "A program checks every item in a list and only counts the ones greater than 10. Which combination of concepts does this use?",
        choices: [
          "A loop with a conditional inside it",
          "A variable with no loop at all",
          "An algorithm with no decisions",
          "A sequence with no repetition",
        ],
        correctChoiceIndex: 0,
        explanation: "Checking every item requires a loop to visit each one, and a conditional to decide whether each item meets the rule.",
      },
    ],
  },
  {
    id: "technology-debugging",
    subject: "technology",
    order: 7,
    title: "Debugging & Testing",
    teachingBlurb:
      "A bug is an error that makes a program behave incorrectly. Debugging is the systematic process of finding and fixing bugs — usually by tracing through the code step by step with sample values to see exactly where the actual result diverges from the expected one. Testing a program with several different inputs (including tricky edge cases) helps catch bugs that only show up in certain situations.",
    questions: [
      {
        id: "technology-debugging-q1",
        type: "multiple-choice",
        prompt: "A 'bug' in a program is...",
        choices: [
          "An error that causes the program to behave incorrectly",
          "A required part of every working program",
          "A type of loop",
          "A comment in the code",
        ],
        correctChoiceIndex: 0,
        explanation: "A bug is any flaw that makes a program produce the wrong result or crash.",
      },
      {
        id: "technology-debugging-q2",
        type: "multiple-choice",
        prompt: "This pseudocode is supposed to print the sum 1+2+3+4+5 = 15:\nSET total = 0\nFOR i FROM 1 TO 5\n  SET total = total + i\nEND FOR\nPRINT total\nA student accidentally wrote 'FOR i FROM 1 TO 4' instead. What would it print?",
        choices: ["10", "15", "20", "4"],
        correctChoiceIndex: 0,
        explanation: "With the loop only running from 1 to 4, it sums 1+2+3+4 = 10 instead of the intended 15.",
      },
      {
        id: "technology-debugging-q3",
        type: "multiple-choice",
        prompt: "What is a good first step when debugging unexpected output?",
        choices: [
          "Trace through the code step by step with sample values to see where it diverges from what you expect",
          "Immediately rewrite the entire program from scratch",
          "Ignore the error and hope it goes away",
          "Delete all the variables in the program",
        ],
        correctChoiceIndex: 0,
        explanation: "Tracing execution by hand, step by step, helps pinpoint exactly which line produces the wrong value.",
      },
      {
        id: "technology-debugging-q4",
        type: "multiple-choice",
        prompt: "A loop that never ends (an infinite loop) is usually caused by...",
        choices: [
          "A condition that never becomes false",
          "Having too many variables",
          "Using an IF statement",
          "Adding comments to the code",
        ],
        correctChoiceIndex: 0,
        explanation: "If nothing inside the loop ever makes the loop's condition false, the loop has no way to stop.",
      },
      {
        id: "technology-debugging-q5",
        type: "multiple-choice",
        prompt: "Why is testing a program with multiple different inputs important?",
        choices: [
          "Because a program might work for one input but fail for another (edge cases)",
          "Because it makes the program run faster",
          "Because it's required to compile the code",
          "Because it changes what the algorithm does",
        ],
        correctChoiceIndex: 0,
        explanation: "Bugs often only appear for specific inputs, like zero, negative numbers, or empty lists — testing multiple cases reveals those.",
      },
      {
        id: "technology-debugging-q6",
        type: "multiple-choice",
        prompt: "A program is supposed to greet users who are 13 or older with 'Teen', but it uses 'IF age > 13' instead of 'IF age >= 13'. What bug does this cause?",
        choices: [
          "A 13-year-old would incorrectly NOT get greeted as a teen",
          "A 13-year-old would correctly get greeted as a teen",
          "The program crashes for every age",
          "Nothing changes — the two conditions are identical",
        ],
        correctChoiceIndex: 0,
        explanation: "'>' excludes 13 itself, while '>=' includes it — so a 13-year-old is wrongly left out of the 'Teen' branch with the buggy condition.",
      },
    ],
  },
];
